
services:

  ms_authorization:
    build: ./
    container_name: ms_authorization
    ports:
      - "8080:80"
    networks:
      - realidad_aumentada
    depends_on:
      - mongo  


  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "57017:27017"
    volumes:
      - db_data_mongo:/data/db
    networks:
      - realidad_aumentada


networks:
  realidad_aumentada:
    driver: bridge

volumes:

  db_data_mongo:
    driver: local
